name: Publish new release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  attach-pyz:
    name: Attach zipapp to the release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up latest python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x.x"

      - name: Build zipapp
        run: |
          python3 -m pip install --upgrade pip
          pip install shiv
          shiv --entry-point moodle_to_vikwikiquiz.main:main --output-file moodle-to-vikwikiquiz.pyz --reproducible .

      - name: Attach the generated zipapp
        uses: svenstaro/upload-release-action@v2
        with:
          file: moodle-to-vikwikiquiz.pyz
          overwrite: true
          asset_name: moodle-to-vikwikiquiz_$tag.pyz

  pypi-publish:
    name: Publish package to PyPI

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up latest python3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x.x"

      - name: Build package
        run: |
          python3 -m pip install --upgrade pip
          pip install build
          python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
