name: Publish new release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  attach-pyz:
    name: Attach `.pyz` to release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.4'

      - name: Build `.pyz`
        run: |
          python3 -m pip install --upgrade pip
          pip install shiv
          shiv --entry-point moodle_to_vikwikiquiz.main:main --output-file moodle-to-vikwikiquiz.pyz --reproducible .

      - name: Attach the generated `.pyz`
        uses: svenstaro/upload-release-action@v2
        with:
          file: moodle-to-vikwikiquiz.pyz
          asset_name: moodle-to-vikwikiquiz_$tag.pyz

  pypi-publish:
    name: Publish package to PyPI

    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.4'

      - name: Build package
        run: |
          python3 -m pip install --upgrade pip
          pip install build
          python3 -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
